{
    'name': 'HR Recruitment Custom',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Customizations for HR Recruitment Processes',
    'depends': ['hr_recruitment','survey', 'hr_recruitment_survey'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/scheduled_actions.xml',
        'data/feedback_survey.xml',
        'data/hr_selection_decision_sequence.xml',
        'views/brand_promotion_templates.xml',
        'views/exam_center_view.xml',
        'views/hr_recruitment_stage_view.xml',
        'views/hr_applicant_view.xml',
        'views/hr_job_view.xml',
        'views/hr_candidate_views.xml',
        'views/survey_view.xml',
        'views/survey_templates_management.xml',
        'views/survey_templates.xml',
        'views/res_company_view.xml',
        'views/hr_selection_decision_view.xml',
        'views/news_views.xml',
        'views/menuitems.xml',
        'wizard/transfer_applicants_view.xml',
        'wizard/candidates_filter_view.xml',
        'wizard/exam_builder_wizard_view.xml',
        'wizard/job_close_wizard_view.xml',
        'report/report_action.xml',
        'wizard/applicant_result_report_wizard.xml',
        'wizard/send_participants_wizard_view.xml',
        'report/applicant_results_template.xml',
        'report/job_results_template.xml',
        'report/interview_form_report.xml',
        'report/hired_selection_decision_report.xml',

        
    ],
    'assets': {
    'web.assets_frontend': [
        'hr_recruitment_custom/static/src/css/answer_color.css',
        #'hr_recruitment_custom/static/src/js/survey_submit_warning.js',
    ],
},
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
